#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-only or GPL-3.0-or-later

# Builds project, moves the executable to top of project directory and runs it

cmake --preset debug
cmake --build --preset debug
mv $(pwd)/build/debug/oglapp $(pwd)/oglapp

./oglapp "$@"
